// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package bot_test

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"github.com/gojuno/minimock/v3"
)

// MessageSenderMock implements MessageSender
type MessageSenderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAckCallback          func(callbackID string) (err error)
	funcAckCallbackOrigin    string
	inspectFuncAckCallback   func(callbackID string)
	afterAckCallbackCounter  uint64
	beforeAckCallbackCounter uint64
	AckCallbackMock          mMessageSenderMockAckCallback

	funcSend          func(chatID int64, text string) (err error)
	funcSendOrigin    string
	inspectFuncSend   func(chatID int64, text string)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mMessageSenderMockSend

	funcSendTyping          func(chatID int64) (err error)
	funcSendTypingOrigin    string
	inspectFuncSendTyping   func(chatID int64)
	afterSendTypingCounter  uint64
	beforeSendTypingCounter uint64
	SendTypingMock          mMessageSenderMockSendTyping

	funcSendWithInlineKeyboard          func(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup) (err error)
	funcSendWithInlineKeyboardOrigin    string
	inspectFuncSendWithInlineKeyboard   func(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup)
	afterSendWithInlineKeyboardCounter  uint64
	beforeSendWithInlineKeyboardCounter uint64
	SendWithInlineKeyboardMock          mMessageSenderMockSendWithInlineKeyboard
}

// NewMessageSenderMock returns a mock for MessageSender
func NewMessageSenderMock(t minimock.Tester) *MessageSenderMock {
	m := &MessageSenderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AckCallbackMock = mMessageSenderMockAckCallback{mock: m}
	m.AckCallbackMock.callArgs = []*MessageSenderMockAckCallbackParams{}

	m.SendMock = mMessageSenderMockSend{mock: m}
	m.SendMock.callArgs = []*MessageSenderMockSendParams{}

	m.SendTypingMock = mMessageSenderMockSendTyping{mock: m}
	m.SendTypingMock.callArgs = []*MessageSenderMockSendTypingParams{}

	m.SendWithInlineKeyboardMock = mMessageSenderMockSendWithInlineKeyboard{mock: m}
	m.SendWithInlineKeyboardMock.callArgs = []*MessageSenderMockSendWithInlineKeyboardParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageSenderMockAckCallback struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockAckCallbackExpectation
	expectations       []*MessageSenderMockAckCallbackExpectation

	callArgs []*MessageSenderMockAckCallbackParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockAckCallbackExpectation specifies expectation struct of the MessageSender.AckCallback
type MessageSenderMockAckCallbackExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockAckCallbackParams
	paramPtrs          *MessageSenderMockAckCallbackParamPtrs
	expectationOrigins MessageSenderMockAckCallbackExpectationOrigins
	results            *MessageSenderMockAckCallbackResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockAckCallbackParams contains parameters of the MessageSender.AckCallback
type MessageSenderMockAckCallbackParams struct {
	callbackID string
}

// MessageSenderMockAckCallbackParamPtrs contains pointers to parameters of the MessageSender.AckCallback
type MessageSenderMockAckCallbackParamPtrs struct {
	callbackID *string
}

// MessageSenderMockAckCallbackResults contains results of the MessageSender.AckCallback
type MessageSenderMockAckCallbackResults struct {
	err error
}

// MessageSenderMockAckCallbackOrigins contains origins of expectations of the MessageSender.AckCallback
type MessageSenderMockAckCallbackExpectationOrigins struct {
	origin           string
	originCallbackID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAckCallback *mMessageSenderMockAckCallback) Optional() *mMessageSenderMockAckCallback {
	mmAckCallback.optional = true
	return mmAckCallback
}

// Expect sets up expected params for MessageSender.AckCallback
func (mmAckCallback *mMessageSenderMockAckCallback) Expect(callbackID string) *mMessageSenderMockAckCallback {
	if mmAckCallback.mock.funcAckCallback != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by Set")
	}

	if mmAckCallback.defaultExpectation == nil {
		mmAckCallback.defaultExpectation = &MessageSenderMockAckCallbackExpectation{}
	}

	if mmAckCallback.defaultExpectation.paramPtrs != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by ExpectParams functions")
	}

	mmAckCallback.defaultExpectation.params = &MessageSenderMockAckCallbackParams{callbackID}
	mmAckCallback.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAckCallback.expectations {
		if minimock.Equal(e.params, mmAckCallback.defaultExpectation.params) {
			mmAckCallback.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAckCallback.defaultExpectation.params)
		}
	}

	return mmAckCallback
}

// ExpectCallbackIDParam1 sets up expected param callbackID for MessageSender.AckCallback
func (mmAckCallback *mMessageSenderMockAckCallback) ExpectCallbackIDParam1(callbackID string) *mMessageSenderMockAckCallback {
	if mmAckCallback.mock.funcAckCallback != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by Set")
	}

	if mmAckCallback.defaultExpectation == nil {
		mmAckCallback.defaultExpectation = &MessageSenderMockAckCallbackExpectation{}
	}

	if mmAckCallback.defaultExpectation.params != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by Expect")
	}

	if mmAckCallback.defaultExpectation.paramPtrs == nil {
		mmAckCallback.defaultExpectation.paramPtrs = &MessageSenderMockAckCallbackParamPtrs{}
	}
	mmAckCallback.defaultExpectation.paramPtrs.callbackID = &callbackID
	mmAckCallback.defaultExpectation.expectationOrigins.originCallbackID = minimock.CallerInfo(1)

	return mmAckCallback
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.AckCallback
func (mmAckCallback *mMessageSenderMockAckCallback) Inspect(f func(callbackID string)) *mMessageSenderMockAckCallback {
	if mmAckCallback.mock.inspectFuncAckCallback != nil {
		mmAckCallback.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.AckCallback")
	}

	mmAckCallback.mock.inspectFuncAckCallback = f

	return mmAckCallback
}

// Return sets up results that will be returned by MessageSender.AckCallback
func (mmAckCallback *mMessageSenderMockAckCallback) Return(err error) *MessageSenderMock {
	if mmAckCallback.mock.funcAckCallback != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by Set")
	}

	if mmAckCallback.defaultExpectation == nil {
		mmAckCallback.defaultExpectation = &MessageSenderMockAckCallbackExpectation{mock: mmAckCallback.mock}
	}
	mmAckCallback.defaultExpectation.results = &MessageSenderMockAckCallbackResults{err}
	mmAckCallback.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAckCallback.mock
}

// Set uses given function f to mock the MessageSender.AckCallback method
func (mmAckCallback *mMessageSenderMockAckCallback) Set(f func(callbackID string) (err error)) *MessageSenderMock {
	if mmAckCallback.defaultExpectation != nil {
		mmAckCallback.mock.t.Fatalf("Default expectation is already set for the MessageSender.AckCallback method")
	}

	if len(mmAckCallback.expectations) > 0 {
		mmAckCallback.mock.t.Fatalf("Some expectations are already set for the MessageSender.AckCallback method")
	}

	mmAckCallback.mock.funcAckCallback = f
	mmAckCallback.mock.funcAckCallbackOrigin = minimock.CallerInfo(1)
	return mmAckCallback.mock
}

// When sets expectation for the MessageSender.AckCallback which will trigger the result defined by the following
// Then helper
func (mmAckCallback *mMessageSenderMockAckCallback) When(callbackID string) *MessageSenderMockAckCallbackExpectation {
	if mmAckCallback.mock.funcAckCallback != nil {
		mmAckCallback.mock.t.Fatalf("MessageSenderMock.AckCallback mock is already set by Set")
	}

	expectation := &MessageSenderMockAckCallbackExpectation{
		mock:               mmAckCallback.mock,
		params:             &MessageSenderMockAckCallbackParams{callbackID},
		expectationOrigins: MessageSenderMockAckCallbackExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAckCallback.expectations = append(mmAckCallback.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.AckCallback return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockAckCallbackExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockAckCallbackResults{err}
	return e.mock
}

// Times sets number of times MessageSender.AckCallback should be invoked
func (mmAckCallback *mMessageSenderMockAckCallback) Times(n uint64) *mMessageSenderMockAckCallback {
	if n == 0 {
		mmAckCallback.mock.t.Fatalf("Times of MessageSenderMock.AckCallback mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAckCallback.expectedInvocations, n)
	mmAckCallback.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAckCallback
}

func (mmAckCallback *mMessageSenderMockAckCallback) invocationsDone() bool {
	if len(mmAckCallback.expectations) == 0 && mmAckCallback.defaultExpectation == nil && mmAckCallback.mock.funcAckCallback == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAckCallback.mock.afterAckCallbackCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAckCallback.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AckCallback implements MessageSender
func (mmAckCallback *MessageSenderMock) AckCallback(callbackID string) (err error) {
	mm_atomic.AddUint64(&mmAckCallback.beforeAckCallbackCounter, 1)
	defer mm_atomic.AddUint64(&mmAckCallback.afterAckCallbackCounter, 1)

	mmAckCallback.t.Helper()

	if mmAckCallback.inspectFuncAckCallback != nil {
		mmAckCallback.inspectFuncAckCallback(callbackID)
	}

	mm_params := MessageSenderMockAckCallbackParams{callbackID}

	// Record call args
	mmAckCallback.AckCallbackMock.mutex.Lock()
	mmAckCallback.AckCallbackMock.callArgs = append(mmAckCallback.AckCallbackMock.callArgs, &mm_params)
	mmAckCallback.AckCallbackMock.mutex.Unlock()

	for _, e := range mmAckCallback.AckCallbackMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAckCallback.AckCallbackMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAckCallback.AckCallbackMock.defaultExpectation.Counter, 1)
		mm_want := mmAckCallback.AckCallbackMock.defaultExpectation.params
		mm_want_ptrs := mmAckCallback.AckCallbackMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockAckCallbackParams{callbackID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.callbackID != nil && !minimock.Equal(*mm_want_ptrs.callbackID, mm_got.callbackID) {
				mmAckCallback.t.Errorf("MessageSenderMock.AckCallback got unexpected parameter callbackID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAckCallback.AckCallbackMock.defaultExpectation.expectationOrigins.originCallbackID, *mm_want_ptrs.callbackID, mm_got.callbackID, minimock.Diff(*mm_want_ptrs.callbackID, mm_got.callbackID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAckCallback.t.Errorf("MessageSenderMock.AckCallback got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAckCallback.AckCallbackMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAckCallback.AckCallbackMock.defaultExpectation.results
		if mm_results == nil {
			mmAckCallback.t.Fatal("No results are set for the MessageSenderMock.AckCallback")
		}
		return (*mm_results).err
	}
	if mmAckCallback.funcAckCallback != nil {
		return mmAckCallback.funcAckCallback(callbackID)
	}
	mmAckCallback.t.Fatalf("Unexpected call to MessageSenderMock.AckCallback. %v", callbackID)
	return
}

// AckCallbackAfterCounter returns a count of finished MessageSenderMock.AckCallback invocations
func (mmAckCallback *MessageSenderMock) AckCallbackAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAckCallback.afterAckCallbackCounter)
}

// AckCallbackBeforeCounter returns a count of MessageSenderMock.AckCallback invocations
func (mmAckCallback *MessageSenderMock) AckCallbackBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAckCallback.beforeAckCallbackCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.AckCallback.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAckCallback *mMessageSenderMockAckCallback) Calls() []*MessageSenderMockAckCallbackParams {
	mmAckCallback.mutex.RLock()

	argCopy := make([]*MessageSenderMockAckCallbackParams, len(mmAckCallback.callArgs))
	copy(argCopy, mmAckCallback.callArgs)

	mmAckCallback.mutex.RUnlock()

	return argCopy
}

// MinimockAckCallbackDone returns true if the count of the AckCallback invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockAckCallbackDone() bool {
	if m.AckCallbackMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AckCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AckCallbackMock.invocationsDone()
}

// MinimockAckCallbackInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockAckCallbackInspect() {
	for _, e := range m.AckCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.AckCallback at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAckCallbackCounter := mm_atomic.LoadUint64(&m.afterAckCallbackCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AckCallbackMock.defaultExpectation != nil && afterAckCallbackCounter < 1 {
		if m.AckCallbackMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.AckCallback at\n%s", m.AckCallbackMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.AckCallback at\n%s with params: %#v", m.AckCallbackMock.defaultExpectation.expectationOrigins.origin, *m.AckCallbackMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAckCallback != nil && afterAckCallbackCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.AckCallback at\n%s", m.funcAckCallbackOrigin)
	}

	if !m.AckCallbackMock.invocationsDone() && afterAckCallbackCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.AckCallback at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AckCallbackMock.expectedInvocations), m.AckCallbackMock.expectedInvocationsOrigin, afterAckCallbackCounter)
	}
}

type mMessageSenderMockSend struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockSendExpectation
	expectations       []*MessageSenderMockSendExpectation

	callArgs []*MessageSenderMockSendParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockSendExpectation specifies expectation struct of the MessageSender.Send
type MessageSenderMockSendExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockSendParams
	paramPtrs          *MessageSenderMockSendParamPtrs
	expectationOrigins MessageSenderMockSendExpectationOrigins
	results            *MessageSenderMockSendResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockSendParams contains parameters of the MessageSender.Send
type MessageSenderMockSendParams struct {
	chatID int64
	text   string
}

// MessageSenderMockSendParamPtrs contains pointers to parameters of the MessageSender.Send
type MessageSenderMockSendParamPtrs struct {
	chatID *int64
	text   *string
}

// MessageSenderMockSendResults contains results of the MessageSender.Send
type MessageSenderMockSendResults struct {
	err error
}

// MessageSenderMockSendOrigins contains origins of expectations of the MessageSender.Send
type MessageSenderMockSendExpectationOrigins struct {
	origin       string
	originChatID string
	originText   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSend *mMessageSenderMockSend) Optional() *mMessageSenderMockSend {
	mmSend.optional = true
	return mmSend
}

// Expect sets up expected params for MessageSender.Send
func (mmSend *mMessageSenderMockSend) Expect(chatID int64, text string) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.paramPtrs != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by ExpectParams functions")
	}

	mmSend.defaultExpectation.params = &MessageSenderMockSendParams{chatID, text}
	mmSend.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// ExpectChatIDParam1 sets up expected param chatID for MessageSender.Send
func (mmSend *mMessageSenderMockSend) ExpectChatIDParam1(chatID int64) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageSenderMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.chatID = &chatID
	mmSend.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmSend
}

// ExpectTextParam2 sets up expected param text for MessageSender.Send
func (mmSend *mMessageSenderMockSend) ExpectTextParam2(text string) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageSenderMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.text = &text
	mmSend.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.Send
func (mmSend *mMessageSenderMockSend) Inspect(f func(chatID int64, text string)) *mMessageSenderMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by MessageSender.Send
func (mmSend *mMessageSenderMockSend) Return(err error) *MessageSenderMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &MessageSenderMockSendResults{err}
	mmSend.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// Set uses given function f to mock the MessageSender.Send method
func (mmSend *mMessageSenderMockSend) Set(f func(chatID int64, text string) (err error)) *MessageSenderMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the MessageSender.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the MessageSender.Send method")
	}

	mmSend.mock.funcSend = f
	mmSend.mock.funcSendOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// When sets expectation for the MessageSender.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mMessageSenderMockSend) When(chatID int64, text string) *MessageSenderMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	expectation := &MessageSenderMockSendExpectation{
		mock:               mmSend.mock,
		params:             &MessageSenderMockSendParams{chatID, text},
		expectationOrigins: MessageSenderMockSendExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.Send return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockSendExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockSendResults{err}
	return e.mock
}

// Times sets number of times MessageSender.Send should be invoked
func (mmSend *mMessageSenderMockSend) Times(n uint64) *mMessageSenderMockSend {
	if n == 0 {
		mmSend.mock.t.Fatalf("Times of MessageSenderMock.Send mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSend.expectedInvocations, n)
	mmSend.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSend
}

func (mmSend *mMessageSenderMockSend) invocationsDone() bool {
	if len(mmSend.expectations) == 0 && mmSend.defaultExpectation == nil && mmSend.mock.funcSend == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSend.mock.afterSendCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSend.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Send implements MessageSender
func (mmSend *MessageSenderMock) Send(chatID int64, text string) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	mmSend.t.Helper()

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(chatID, text)
	}

	mm_params := MessageSenderMockSendParams{chatID, text}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, &mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_want_ptrs := mmSend.SendMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockSendParams{chatID, text}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSend.SendMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the MessageSenderMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(chatID, text)
	}
	mmSend.t.Fatalf("Unexpected call to MessageSenderMock.Send. %v %v", chatID, text)
	return
}

// SendAfterCounter returns a count of finished MessageSenderMock.Send invocations
func (mmSend *MessageSenderMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of MessageSenderMock.Send invocations
func (mmSend *MessageSenderMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mMessageSenderMockSend) Calls() []*MessageSenderMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*MessageSenderMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockSendDone() bool {
	if m.SendMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMock.invocationsDone()
}

// MinimockSendInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendCounter := mm_atomic.LoadUint64(&m.afterSendCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && afterSendCounter < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s", m.SendMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s with params: %#v", m.SendMock.defaultExpectation.expectationOrigins.origin, *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && afterSendCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s", m.funcSendOrigin)
	}

	if !m.SendMock.invocationsDone() && afterSendCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.Send at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMock.expectedInvocations), m.SendMock.expectedInvocationsOrigin, afterSendCounter)
	}
}

type mMessageSenderMockSendTyping struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockSendTypingExpectation
	expectations       []*MessageSenderMockSendTypingExpectation

	callArgs []*MessageSenderMockSendTypingParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockSendTypingExpectation specifies expectation struct of the MessageSender.SendTyping
type MessageSenderMockSendTypingExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockSendTypingParams
	paramPtrs          *MessageSenderMockSendTypingParamPtrs
	expectationOrigins MessageSenderMockSendTypingExpectationOrigins
	results            *MessageSenderMockSendTypingResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockSendTypingParams contains parameters of the MessageSender.SendTyping
type MessageSenderMockSendTypingParams struct {
	chatID int64
}

// MessageSenderMockSendTypingParamPtrs contains pointers to parameters of the MessageSender.SendTyping
type MessageSenderMockSendTypingParamPtrs struct {
	chatID *int64
}

// MessageSenderMockSendTypingResults contains results of the MessageSender.SendTyping
type MessageSenderMockSendTypingResults struct {
	err error
}

// MessageSenderMockSendTypingOrigins contains origins of expectations of the MessageSender.SendTyping
type MessageSenderMockSendTypingExpectationOrigins struct {
	origin       string
	originChatID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendTyping *mMessageSenderMockSendTyping) Optional() *mMessageSenderMockSendTyping {
	mmSendTyping.optional = true
	return mmSendTyping
}

// Expect sets up expected params for MessageSender.SendTyping
func (mmSendTyping *mMessageSenderMockSendTyping) Expect(chatID int64) *mMessageSenderMockSendTyping {
	if mmSendTyping.mock.funcSendTyping != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by Set")
	}

	if mmSendTyping.defaultExpectation == nil {
		mmSendTyping.defaultExpectation = &MessageSenderMockSendTypingExpectation{}
	}

	if mmSendTyping.defaultExpectation.paramPtrs != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by ExpectParams functions")
	}

	mmSendTyping.defaultExpectation.params = &MessageSenderMockSendTypingParams{chatID}
	mmSendTyping.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendTyping.expectations {
		if minimock.Equal(e.params, mmSendTyping.defaultExpectation.params) {
			mmSendTyping.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendTyping.defaultExpectation.params)
		}
	}

	return mmSendTyping
}

// ExpectChatIDParam1 sets up expected param chatID for MessageSender.SendTyping
func (mmSendTyping *mMessageSenderMockSendTyping) ExpectChatIDParam1(chatID int64) *mMessageSenderMockSendTyping {
	if mmSendTyping.mock.funcSendTyping != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by Set")
	}

	if mmSendTyping.defaultExpectation == nil {
		mmSendTyping.defaultExpectation = &MessageSenderMockSendTypingExpectation{}
	}

	if mmSendTyping.defaultExpectation.params != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by Expect")
	}

	if mmSendTyping.defaultExpectation.paramPtrs == nil {
		mmSendTyping.defaultExpectation.paramPtrs = &MessageSenderMockSendTypingParamPtrs{}
	}
	mmSendTyping.defaultExpectation.paramPtrs.chatID = &chatID
	mmSendTyping.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmSendTyping
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.SendTyping
func (mmSendTyping *mMessageSenderMockSendTyping) Inspect(f func(chatID int64)) *mMessageSenderMockSendTyping {
	if mmSendTyping.mock.inspectFuncSendTyping != nil {
		mmSendTyping.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.SendTyping")
	}

	mmSendTyping.mock.inspectFuncSendTyping = f

	return mmSendTyping
}

// Return sets up results that will be returned by MessageSender.SendTyping
func (mmSendTyping *mMessageSenderMockSendTyping) Return(err error) *MessageSenderMock {
	if mmSendTyping.mock.funcSendTyping != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by Set")
	}

	if mmSendTyping.defaultExpectation == nil {
		mmSendTyping.defaultExpectation = &MessageSenderMockSendTypingExpectation{mock: mmSendTyping.mock}
	}
	mmSendTyping.defaultExpectation.results = &MessageSenderMockSendTypingResults{err}
	mmSendTyping.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendTyping.mock
}

// Set uses given function f to mock the MessageSender.SendTyping method
func (mmSendTyping *mMessageSenderMockSendTyping) Set(f func(chatID int64) (err error)) *MessageSenderMock {
	if mmSendTyping.defaultExpectation != nil {
		mmSendTyping.mock.t.Fatalf("Default expectation is already set for the MessageSender.SendTyping method")
	}

	if len(mmSendTyping.expectations) > 0 {
		mmSendTyping.mock.t.Fatalf("Some expectations are already set for the MessageSender.SendTyping method")
	}

	mmSendTyping.mock.funcSendTyping = f
	mmSendTyping.mock.funcSendTypingOrigin = minimock.CallerInfo(1)
	return mmSendTyping.mock
}

// When sets expectation for the MessageSender.SendTyping which will trigger the result defined by the following
// Then helper
func (mmSendTyping *mMessageSenderMockSendTyping) When(chatID int64) *MessageSenderMockSendTypingExpectation {
	if mmSendTyping.mock.funcSendTyping != nil {
		mmSendTyping.mock.t.Fatalf("MessageSenderMock.SendTyping mock is already set by Set")
	}

	expectation := &MessageSenderMockSendTypingExpectation{
		mock:               mmSendTyping.mock,
		params:             &MessageSenderMockSendTypingParams{chatID},
		expectationOrigins: MessageSenderMockSendTypingExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendTyping.expectations = append(mmSendTyping.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.SendTyping return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockSendTypingExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockSendTypingResults{err}
	return e.mock
}

// Times sets number of times MessageSender.SendTyping should be invoked
func (mmSendTyping *mMessageSenderMockSendTyping) Times(n uint64) *mMessageSenderMockSendTyping {
	if n == 0 {
		mmSendTyping.mock.t.Fatalf("Times of MessageSenderMock.SendTyping mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendTyping.expectedInvocations, n)
	mmSendTyping.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendTyping
}

func (mmSendTyping *mMessageSenderMockSendTyping) invocationsDone() bool {
	if len(mmSendTyping.expectations) == 0 && mmSendTyping.defaultExpectation == nil && mmSendTyping.mock.funcSendTyping == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendTyping.mock.afterSendTypingCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendTyping.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendTyping implements MessageSender
func (mmSendTyping *MessageSenderMock) SendTyping(chatID int64) (err error) {
	mm_atomic.AddUint64(&mmSendTyping.beforeSendTypingCounter, 1)
	defer mm_atomic.AddUint64(&mmSendTyping.afterSendTypingCounter, 1)

	mmSendTyping.t.Helper()

	if mmSendTyping.inspectFuncSendTyping != nil {
		mmSendTyping.inspectFuncSendTyping(chatID)
	}

	mm_params := MessageSenderMockSendTypingParams{chatID}

	// Record call args
	mmSendTyping.SendTypingMock.mutex.Lock()
	mmSendTyping.SendTypingMock.callArgs = append(mmSendTyping.SendTypingMock.callArgs, &mm_params)
	mmSendTyping.SendTypingMock.mutex.Unlock()

	for _, e := range mmSendTyping.SendTypingMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendTyping.SendTypingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendTyping.SendTypingMock.defaultExpectation.Counter, 1)
		mm_want := mmSendTyping.SendTypingMock.defaultExpectation.params
		mm_want_ptrs := mmSendTyping.SendTypingMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockSendTypingParams{chatID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmSendTyping.t.Errorf("MessageSenderMock.SendTyping got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendTyping.SendTypingMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendTyping.t.Errorf("MessageSenderMock.SendTyping got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendTyping.SendTypingMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendTyping.SendTypingMock.defaultExpectation.results
		if mm_results == nil {
			mmSendTyping.t.Fatal("No results are set for the MessageSenderMock.SendTyping")
		}
		return (*mm_results).err
	}
	if mmSendTyping.funcSendTyping != nil {
		return mmSendTyping.funcSendTyping(chatID)
	}
	mmSendTyping.t.Fatalf("Unexpected call to MessageSenderMock.SendTyping. %v", chatID)
	return
}

// SendTypingAfterCounter returns a count of finished MessageSenderMock.SendTyping invocations
func (mmSendTyping *MessageSenderMock) SendTypingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendTyping.afterSendTypingCounter)
}

// SendTypingBeforeCounter returns a count of MessageSenderMock.SendTyping invocations
func (mmSendTyping *MessageSenderMock) SendTypingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendTyping.beforeSendTypingCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.SendTyping.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendTyping *mMessageSenderMockSendTyping) Calls() []*MessageSenderMockSendTypingParams {
	mmSendTyping.mutex.RLock()

	argCopy := make([]*MessageSenderMockSendTypingParams, len(mmSendTyping.callArgs))
	copy(argCopy, mmSendTyping.callArgs)

	mmSendTyping.mutex.RUnlock()

	return argCopy
}

// MinimockSendTypingDone returns true if the count of the SendTyping invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockSendTypingDone() bool {
	if m.SendTypingMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendTypingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendTypingMock.invocationsDone()
}

// MinimockSendTypingInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockSendTypingInspect() {
	for _, e := range m.SendTypingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.SendTyping at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendTypingCounter := mm_atomic.LoadUint64(&m.afterSendTypingCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendTypingMock.defaultExpectation != nil && afterSendTypingCounter < 1 {
		if m.SendTypingMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.SendTyping at\n%s", m.SendTypingMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.SendTyping at\n%s with params: %#v", m.SendTypingMock.defaultExpectation.expectationOrigins.origin, *m.SendTypingMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendTyping != nil && afterSendTypingCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.SendTyping at\n%s", m.funcSendTypingOrigin)
	}

	if !m.SendTypingMock.invocationsDone() && afterSendTypingCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.SendTyping at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendTypingMock.expectedInvocations), m.SendTypingMock.expectedInvocationsOrigin, afterSendTypingCounter)
	}
}

type mMessageSenderMockSendWithInlineKeyboard struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockSendWithInlineKeyboardExpectation
	expectations       []*MessageSenderMockSendWithInlineKeyboardExpectation

	callArgs []*MessageSenderMockSendWithInlineKeyboardParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockSendWithInlineKeyboardExpectation specifies expectation struct of the MessageSender.SendWithInlineKeyboard
type MessageSenderMockSendWithInlineKeyboardExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockSendWithInlineKeyboardParams
	paramPtrs          *MessageSenderMockSendWithInlineKeyboardParamPtrs
	expectationOrigins MessageSenderMockSendWithInlineKeyboardExpectationOrigins
	results            *MessageSenderMockSendWithInlineKeyboardResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockSendWithInlineKeyboardParams contains parameters of the MessageSender.SendWithInlineKeyboard
type MessageSenderMockSendWithInlineKeyboardParams struct {
	chatID   int64
	text     string
	keyboard tgbotapi.InlineKeyboardMarkup
}

// MessageSenderMockSendWithInlineKeyboardParamPtrs contains pointers to parameters of the MessageSender.SendWithInlineKeyboard
type MessageSenderMockSendWithInlineKeyboardParamPtrs struct {
	chatID   *int64
	text     *string
	keyboard *tgbotapi.InlineKeyboardMarkup
}

// MessageSenderMockSendWithInlineKeyboardResults contains results of the MessageSender.SendWithInlineKeyboard
type MessageSenderMockSendWithInlineKeyboardResults struct {
	err error
}

// MessageSenderMockSendWithInlineKeyboardOrigins contains origins of expectations of the MessageSender.SendWithInlineKeyboard
type MessageSenderMockSendWithInlineKeyboardExpectationOrigins struct {
	origin         string
	originChatID   string
	originText     string
	originKeyboard string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Optional() *mMessageSenderMockSendWithInlineKeyboard {
	mmSendWithInlineKeyboard.optional = true
	return mmSendWithInlineKeyboard
}

// Expect sets up expected params for MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Expect(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup) *mMessageSenderMockSendWithInlineKeyboard {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	if mmSendWithInlineKeyboard.defaultExpectation == nil {
		mmSendWithInlineKeyboard.defaultExpectation = &MessageSenderMockSendWithInlineKeyboardExpectation{}
	}

	if mmSendWithInlineKeyboard.defaultExpectation.paramPtrs != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by ExpectParams functions")
	}

	mmSendWithInlineKeyboard.defaultExpectation.params = &MessageSenderMockSendWithInlineKeyboardParams{chatID, text, keyboard}
	mmSendWithInlineKeyboard.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendWithInlineKeyboard.expectations {
		if minimock.Equal(e.params, mmSendWithInlineKeyboard.defaultExpectation.params) {
			mmSendWithInlineKeyboard.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendWithInlineKeyboard.defaultExpectation.params)
		}
	}

	return mmSendWithInlineKeyboard
}

// ExpectChatIDParam1 sets up expected param chatID for MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) ExpectChatIDParam1(chatID int64) *mMessageSenderMockSendWithInlineKeyboard {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	if mmSendWithInlineKeyboard.defaultExpectation == nil {
		mmSendWithInlineKeyboard.defaultExpectation = &MessageSenderMockSendWithInlineKeyboardExpectation{}
	}

	if mmSendWithInlineKeyboard.defaultExpectation.params != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Expect")
	}

	if mmSendWithInlineKeyboard.defaultExpectation.paramPtrs == nil {
		mmSendWithInlineKeyboard.defaultExpectation.paramPtrs = &MessageSenderMockSendWithInlineKeyboardParamPtrs{}
	}
	mmSendWithInlineKeyboard.defaultExpectation.paramPtrs.chatID = &chatID
	mmSendWithInlineKeyboard.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmSendWithInlineKeyboard
}

// ExpectTextParam2 sets up expected param text for MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) ExpectTextParam2(text string) *mMessageSenderMockSendWithInlineKeyboard {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	if mmSendWithInlineKeyboard.defaultExpectation == nil {
		mmSendWithInlineKeyboard.defaultExpectation = &MessageSenderMockSendWithInlineKeyboardExpectation{}
	}

	if mmSendWithInlineKeyboard.defaultExpectation.params != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Expect")
	}

	if mmSendWithInlineKeyboard.defaultExpectation.paramPtrs == nil {
		mmSendWithInlineKeyboard.defaultExpectation.paramPtrs = &MessageSenderMockSendWithInlineKeyboardParamPtrs{}
	}
	mmSendWithInlineKeyboard.defaultExpectation.paramPtrs.text = &text
	mmSendWithInlineKeyboard.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmSendWithInlineKeyboard
}

// ExpectKeyboardParam3 sets up expected param keyboard for MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) ExpectKeyboardParam3(keyboard tgbotapi.InlineKeyboardMarkup) *mMessageSenderMockSendWithInlineKeyboard {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	if mmSendWithInlineKeyboard.defaultExpectation == nil {
		mmSendWithInlineKeyboard.defaultExpectation = &MessageSenderMockSendWithInlineKeyboardExpectation{}
	}

	if mmSendWithInlineKeyboard.defaultExpectation.params != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Expect")
	}

	if mmSendWithInlineKeyboard.defaultExpectation.paramPtrs == nil {
		mmSendWithInlineKeyboard.defaultExpectation.paramPtrs = &MessageSenderMockSendWithInlineKeyboardParamPtrs{}
	}
	mmSendWithInlineKeyboard.defaultExpectation.paramPtrs.keyboard = &keyboard
	mmSendWithInlineKeyboard.defaultExpectation.expectationOrigins.originKeyboard = minimock.CallerInfo(1)

	return mmSendWithInlineKeyboard
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Inspect(f func(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup)) *mMessageSenderMockSendWithInlineKeyboard {
	if mmSendWithInlineKeyboard.mock.inspectFuncSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.SendWithInlineKeyboard")
	}

	mmSendWithInlineKeyboard.mock.inspectFuncSendWithInlineKeyboard = f

	return mmSendWithInlineKeyboard
}

// Return sets up results that will be returned by MessageSender.SendWithInlineKeyboard
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Return(err error) *MessageSenderMock {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	if mmSendWithInlineKeyboard.defaultExpectation == nil {
		mmSendWithInlineKeyboard.defaultExpectation = &MessageSenderMockSendWithInlineKeyboardExpectation{mock: mmSendWithInlineKeyboard.mock}
	}
	mmSendWithInlineKeyboard.defaultExpectation.results = &MessageSenderMockSendWithInlineKeyboardResults{err}
	mmSendWithInlineKeyboard.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendWithInlineKeyboard.mock
}

// Set uses given function f to mock the MessageSender.SendWithInlineKeyboard method
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Set(f func(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup) (err error)) *MessageSenderMock {
	if mmSendWithInlineKeyboard.defaultExpectation != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("Default expectation is already set for the MessageSender.SendWithInlineKeyboard method")
	}

	if len(mmSendWithInlineKeyboard.expectations) > 0 {
		mmSendWithInlineKeyboard.mock.t.Fatalf("Some expectations are already set for the MessageSender.SendWithInlineKeyboard method")
	}

	mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard = f
	mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboardOrigin = minimock.CallerInfo(1)
	return mmSendWithInlineKeyboard.mock
}

// When sets expectation for the MessageSender.SendWithInlineKeyboard which will trigger the result defined by the following
// Then helper
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) When(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup) *MessageSenderMockSendWithInlineKeyboardExpectation {
	if mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.mock.t.Fatalf("MessageSenderMock.SendWithInlineKeyboard mock is already set by Set")
	}

	expectation := &MessageSenderMockSendWithInlineKeyboardExpectation{
		mock:               mmSendWithInlineKeyboard.mock,
		params:             &MessageSenderMockSendWithInlineKeyboardParams{chatID, text, keyboard},
		expectationOrigins: MessageSenderMockSendWithInlineKeyboardExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendWithInlineKeyboard.expectations = append(mmSendWithInlineKeyboard.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.SendWithInlineKeyboard return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockSendWithInlineKeyboardExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockSendWithInlineKeyboardResults{err}
	return e.mock
}

// Times sets number of times MessageSender.SendWithInlineKeyboard should be invoked
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Times(n uint64) *mMessageSenderMockSendWithInlineKeyboard {
	if n == 0 {
		mmSendWithInlineKeyboard.mock.t.Fatalf("Times of MessageSenderMock.SendWithInlineKeyboard mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendWithInlineKeyboard.expectedInvocations, n)
	mmSendWithInlineKeyboard.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendWithInlineKeyboard
}

func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) invocationsDone() bool {
	if len(mmSendWithInlineKeyboard.expectations) == 0 && mmSendWithInlineKeyboard.defaultExpectation == nil && mmSendWithInlineKeyboard.mock.funcSendWithInlineKeyboard == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendWithInlineKeyboard.mock.afterSendWithInlineKeyboardCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendWithInlineKeyboard.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendWithInlineKeyboard implements MessageSender
func (mmSendWithInlineKeyboard *MessageSenderMock) SendWithInlineKeyboard(chatID int64, text string, keyboard tgbotapi.InlineKeyboardMarkup) (err error) {
	mm_atomic.AddUint64(&mmSendWithInlineKeyboard.beforeSendWithInlineKeyboardCounter, 1)
	defer mm_atomic.AddUint64(&mmSendWithInlineKeyboard.afterSendWithInlineKeyboardCounter, 1)

	mmSendWithInlineKeyboard.t.Helper()

	if mmSendWithInlineKeyboard.inspectFuncSendWithInlineKeyboard != nil {
		mmSendWithInlineKeyboard.inspectFuncSendWithInlineKeyboard(chatID, text, keyboard)
	}

	mm_params := MessageSenderMockSendWithInlineKeyboardParams{chatID, text, keyboard}

	// Record call args
	mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.mutex.Lock()
	mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.callArgs = append(mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.callArgs, &mm_params)
	mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.mutex.Unlock()

	for _, e := range mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.Counter, 1)
		mm_want := mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.params
		mm_want_ptrs := mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockSendWithInlineKeyboardParams{chatID, text, keyboard}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmSendWithInlineKeyboard.t.Errorf("MessageSenderMock.SendWithInlineKeyboard got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmSendWithInlineKeyboard.t.Errorf("MessageSenderMock.SendWithInlineKeyboard got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

			if mm_want_ptrs.keyboard != nil && !minimock.Equal(*mm_want_ptrs.keyboard, mm_got.keyboard) {
				mmSendWithInlineKeyboard.t.Errorf("MessageSenderMock.SendWithInlineKeyboard got unexpected parameter keyboard, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.expectationOrigins.originKeyboard, *mm_want_ptrs.keyboard, mm_got.keyboard, minimock.Diff(*mm_want_ptrs.keyboard, mm_got.keyboard))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendWithInlineKeyboard.t.Errorf("MessageSenderMock.SendWithInlineKeyboard got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendWithInlineKeyboard.SendWithInlineKeyboardMock.defaultExpectation.results
		if mm_results == nil {
			mmSendWithInlineKeyboard.t.Fatal("No results are set for the MessageSenderMock.SendWithInlineKeyboard")
		}
		return (*mm_results).err
	}
	if mmSendWithInlineKeyboard.funcSendWithInlineKeyboard != nil {
		return mmSendWithInlineKeyboard.funcSendWithInlineKeyboard(chatID, text, keyboard)
	}
	mmSendWithInlineKeyboard.t.Fatalf("Unexpected call to MessageSenderMock.SendWithInlineKeyboard. %v %v %v", chatID, text, keyboard)
	return
}

// SendWithInlineKeyboardAfterCounter returns a count of finished MessageSenderMock.SendWithInlineKeyboard invocations
func (mmSendWithInlineKeyboard *MessageSenderMock) SendWithInlineKeyboardAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendWithInlineKeyboard.afterSendWithInlineKeyboardCounter)
}

// SendWithInlineKeyboardBeforeCounter returns a count of MessageSenderMock.SendWithInlineKeyboard invocations
func (mmSendWithInlineKeyboard *MessageSenderMock) SendWithInlineKeyboardBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendWithInlineKeyboard.beforeSendWithInlineKeyboardCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.SendWithInlineKeyboard.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendWithInlineKeyboard *mMessageSenderMockSendWithInlineKeyboard) Calls() []*MessageSenderMockSendWithInlineKeyboardParams {
	mmSendWithInlineKeyboard.mutex.RLock()

	argCopy := make([]*MessageSenderMockSendWithInlineKeyboardParams, len(mmSendWithInlineKeyboard.callArgs))
	copy(argCopy, mmSendWithInlineKeyboard.callArgs)

	mmSendWithInlineKeyboard.mutex.RUnlock()

	return argCopy
}

// MinimockSendWithInlineKeyboardDone returns true if the count of the SendWithInlineKeyboard invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockSendWithInlineKeyboardDone() bool {
	if m.SendWithInlineKeyboardMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendWithInlineKeyboardMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendWithInlineKeyboardMock.invocationsDone()
}

// MinimockSendWithInlineKeyboardInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockSendWithInlineKeyboardInspect() {
	for _, e := range m.SendWithInlineKeyboardMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.SendWithInlineKeyboard at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendWithInlineKeyboardCounter := mm_atomic.LoadUint64(&m.afterSendWithInlineKeyboardCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendWithInlineKeyboardMock.defaultExpectation != nil && afterSendWithInlineKeyboardCounter < 1 {
		if m.SendWithInlineKeyboardMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.SendWithInlineKeyboard at\n%s", m.SendWithInlineKeyboardMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.SendWithInlineKeyboard at\n%s with params: %#v", m.SendWithInlineKeyboardMock.defaultExpectation.expectationOrigins.origin, *m.SendWithInlineKeyboardMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendWithInlineKeyboard != nil && afterSendWithInlineKeyboardCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.SendWithInlineKeyboard at\n%s", m.funcSendWithInlineKeyboardOrigin)
	}

	if !m.SendWithInlineKeyboardMock.invocationsDone() && afterSendWithInlineKeyboardCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.SendWithInlineKeyboard at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendWithInlineKeyboardMock.expectedInvocations), m.SendWithInlineKeyboardMock.expectedInvocationsOrigin, afterSendWithInlineKeyboardCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageSenderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAckCallbackInspect()

			m.MinimockSendInspect()

			m.MinimockSendTypingInspect()

			m.MinimockSendWithInlineKeyboardInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageSenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageSenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAckCallbackDone() &&
		m.MinimockSendDone() &&
		m.MinimockSendTypingDone() &&
		m.MinimockSendWithInlineKeyboardDone()
}
