// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package bot_test

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// MessageSenderMock implements MessageSender
type MessageSenderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSend          func(chatID int64, text string) (err error)
	funcSendOrigin    string
	inspectFuncSend   func(chatID int64, text string)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mMessageSenderMockSend
}

// NewMessageSenderMock returns a mock for MessageSender
func NewMessageSenderMock(t minimock.Tester) *MessageSenderMock {
	m := &MessageSenderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mMessageSenderMockSend{mock: m}
	m.SendMock.callArgs = []*MessageSenderMockSendParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageSenderMockSend struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockSendExpectation
	expectations       []*MessageSenderMockSendExpectation

	callArgs []*MessageSenderMockSendParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockSendExpectation specifies expectation struct of the MessageSender.Send
type MessageSenderMockSendExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockSendParams
	paramPtrs          *MessageSenderMockSendParamPtrs
	expectationOrigins MessageSenderMockSendExpectationOrigins
	results            *MessageSenderMockSendResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockSendParams contains parameters of the MessageSender.Send
type MessageSenderMockSendParams struct {
	chatID int64
	text   string
}

// MessageSenderMockSendParamPtrs contains pointers to parameters of the MessageSender.Send
type MessageSenderMockSendParamPtrs struct {
	chatID *int64
	text   *string
}

// MessageSenderMockSendResults contains results of the MessageSender.Send
type MessageSenderMockSendResults struct {
	err error
}

// MessageSenderMockSendOrigins contains origins of expectations of the MessageSender.Send
type MessageSenderMockSendExpectationOrigins struct {
	origin       string
	originChatID string
	originText   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSend *mMessageSenderMockSend) Optional() *mMessageSenderMockSend {
	mmSend.optional = true
	return mmSend
}

// Expect sets up expected params for MessageSender.Send
func (mmSend *mMessageSenderMockSend) Expect(chatID int64, text string) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.paramPtrs != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by ExpectParams functions")
	}

	mmSend.defaultExpectation.params = &MessageSenderMockSendParams{chatID, text}
	mmSend.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// ExpectChatIDParam1 sets up expected param chatID for MessageSender.Send
func (mmSend *mMessageSenderMockSend) ExpectChatIDParam1(chatID int64) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageSenderMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.chatID = &chatID
	mmSend.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmSend
}

// ExpectTextParam2 sets up expected param text for MessageSender.Send
func (mmSend *mMessageSenderMockSend) ExpectTextParam2(text string) *mMessageSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageSenderMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.text = &text
	mmSend.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.Send
func (mmSend *mMessageSenderMockSend) Inspect(f func(chatID int64, text string)) *mMessageSenderMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by MessageSender.Send
func (mmSend *mMessageSenderMockSend) Return(err error) *MessageSenderMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageSenderMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &MessageSenderMockSendResults{err}
	mmSend.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// Set uses given function f to mock the MessageSender.Send method
func (mmSend *mMessageSenderMockSend) Set(f func(chatID int64, text string) (err error)) *MessageSenderMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the MessageSender.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the MessageSender.Send method")
	}

	mmSend.mock.funcSend = f
	mmSend.mock.funcSendOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// When sets expectation for the MessageSender.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mMessageSenderMockSend) When(chatID int64, text string) *MessageSenderMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageSenderMock.Send mock is already set by Set")
	}

	expectation := &MessageSenderMockSendExpectation{
		mock:               mmSend.mock,
		params:             &MessageSenderMockSendParams{chatID, text},
		expectationOrigins: MessageSenderMockSendExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.Send return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockSendExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockSendResults{err}
	return e.mock
}

// Times sets number of times MessageSender.Send should be invoked
func (mmSend *mMessageSenderMockSend) Times(n uint64) *mMessageSenderMockSend {
	if n == 0 {
		mmSend.mock.t.Fatalf("Times of MessageSenderMock.Send mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSend.expectedInvocations, n)
	mmSend.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSend
}

func (mmSend *mMessageSenderMockSend) invocationsDone() bool {
	if len(mmSend.expectations) == 0 && mmSend.defaultExpectation == nil && mmSend.mock.funcSend == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSend.mock.afterSendCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSend.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Send implements MessageSender
func (mmSend *MessageSenderMock) Send(chatID int64, text string) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	mmSend.t.Helper()

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(chatID, text)
	}

	mm_params := MessageSenderMockSendParams{chatID, text}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, &mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_want_ptrs := mmSend.SendMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockSendParams{chatID, text}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("MessageSenderMock.Send got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSend.SendMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the MessageSenderMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(chatID, text)
	}
	mmSend.t.Fatalf("Unexpected call to MessageSenderMock.Send. %v %v", chatID, text)
	return
}

// SendAfterCounter returns a count of finished MessageSenderMock.Send invocations
func (mmSend *MessageSenderMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of MessageSenderMock.Send invocations
func (mmSend *MessageSenderMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mMessageSenderMockSend) Calls() []*MessageSenderMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*MessageSenderMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockSendDone() bool {
	if m.SendMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMock.invocationsDone()
}

// MinimockSendInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendCounter := mm_atomic.LoadUint64(&m.afterSendCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && afterSendCounter < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s", m.SendMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s with params: %#v", m.SendMock.defaultExpectation.expectationOrigins.origin, *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && afterSendCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.Send at\n%s", m.funcSendOrigin)
	}

	if !m.SendMock.invocationsDone() && afterSendCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.Send at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMock.expectedInvocations), m.SendMock.expectedInvocationsOrigin, afterSendCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageSenderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageSenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageSenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
