// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package bot

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OpenerMock implements opener
type OpenerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcOpen          func(url string) (err error)
	funcOpenOrigin    string
	inspectFuncOpen   func(url string)
	afterOpenCounter  uint64
	beforeOpenCounter uint64
	OpenMock          mOpenerMockOpen
}

// NewOpenerMock returns a mock for opener
func NewOpenerMock(t minimock.Tester) *OpenerMock {
	m := &OpenerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.OpenMock = mOpenerMockOpen{mock: m}
	m.OpenMock.callArgs = []*OpenerMockOpenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOpenerMockOpen struct {
	optional           bool
	mock               *OpenerMock
	defaultExpectation *OpenerMockOpenExpectation
	expectations       []*OpenerMockOpenExpectation

	callArgs []*OpenerMockOpenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OpenerMockOpenExpectation specifies expectation struct of the opener.Open
type OpenerMockOpenExpectation struct {
	mock               *OpenerMock
	params             *OpenerMockOpenParams
	paramPtrs          *OpenerMockOpenParamPtrs
	expectationOrigins OpenerMockOpenExpectationOrigins
	results            *OpenerMockOpenResults
	returnOrigin       string
	Counter            uint64
}

// OpenerMockOpenParams contains parameters of the opener.Open
type OpenerMockOpenParams struct {
	url string
}

// OpenerMockOpenParamPtrs contains pointers to parameters of the opener.Open
type OpenerMockOpenParamPtrs struct {
	url *string
}

// OpenerMockOpenResults contains results of the opener.Open
type OpenerMockOpenResults struct {
	err error
}

// OpenerMockOpenOrigins contains origins of expectations of the opener.Open
type OpenerMockOpenExpectationOrigins struct {
	origin    string
	originUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOpen *mOpenerMockOpen) Optional() *mOpenerMockOpen {
	mmOpen.optional = true
	return mmOpen
}

// Expect sets up expected params for opener.Open
func (mmOpen *mOpenerMockOpen) Expect(url string) *mOpenerMockOpen {
	if mmOpen.mock.funcOpen != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by Set")
	}

	if mmOpen.defaultExpectation == nil {
		mmOpen.defaultExpectation = &OpenerMockOpenExpectation{}
	}

	if mmOpen.defaultExpectation.paramPtrs != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by ExpectParams functions")
	}

	mmOpen.defaultExpectation.params = &OpenerMockOpenParams{url}
	mmOpen.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOpen.expectations {
		if minimock.Equal(e.params, mmOpen.defaultExpectation.params) {
			mmOpen.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOpen.defaultExpectation.params)
		}
	}

	return mmOpen
}

// ExpectUrlParam1 sets up expected param url for opener.Open
func (mmOpen *mOpenerMockOpen) ExpectUrlParam1(url string) *mOpenerMockOpen {
	if mmOpen.mock.funcOpen != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by Set")
	}

	if mmOpen.defaultExpectation == nil {
		mmOpen.defaultExpectation = &OpenerMockOpenExpectation{}
	}

	if mmOpen.defaultExpectation.params != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by Expect")
	}

	if mmOpen.defaultExpectation.paramPtrs == nil {
		mmOpen.defaultExpectation.paramPtrs = &OpenerMockOpenParamPtrs{}
	}
	mmOpen.defaultExpectation.paramPtrs.url = &url
	mmOpen.defaultExpectation.expectationOrigins.originUrl = minimock.CallerInfo(1)

	return mmOpen
}

// Inspect accepts an inspector function that has same arguments as the opener.Open
func (mmOpen *mOpenerMockOpen) Inspect(f func(url string)) *mOpenerMockOpen {
	if mmOpen.mock.inspectFuncOpen != nil {
		mmOpen.mock.t.Fatalf("Inspect function is already set for OpenerMock.Open")
	}

	mmOpen.mock.inspectFuncOpen = f

	return mmOpen
}

// Return sets up results that will be returned by opener.Open
func (mmOpen *mOpenerMockOpen) Return(err error) *OpenerMock {
	if mmOpen.mock.funcOpen != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by Set")
	}

	if mmOpen.defaultExpectation == nil {
		mmOpen.defaultExpectation = &OpenerMockOpenExpectation{mock: mmOpen.mock}
	}
	mmOpen.defaultExpectation.results = &OpenerMockOpenResults{err}
	mmOpen.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOpen.mock
}

// Set uses given function f to mock the opener.Open method
func (mmOpen *mOpenerMockOpen) Set(f func(url string) (err error)) *OpenerMock {
	if mmOpen.defaultExpectation != nil {
		mmOpen.mock.t.Fatalf("Default expectation is already set for the opener.Open method")
	}

	if len(mmOpen.expectations) > 0 {
		mmOpen.mock.t.Fatalf("Some expectations are already set for the opener.Open method")
	}

	mmOpen.mock.funcOpen = f
	mmOpen.mock.funcOpenOrigin = minimock.CallerInfo(1)
	return mmOpen.mock
}

// When sets expectation for the opener.Open which will trigger the result defined by the following
// Then helper
func (mmOpen *mOpenerMockOpen) When(url string) *OpenerMockOpenExpectation {
	if mmOpen.mock.funcOpen != nil {
		mmOpen.mock.t.Fatalf("OpenerMock.Open mock is already set by Set")
	}

	expectation := &OpenerMockOpenExpectation{
		mock:               mmOpen.mock,
		params:             &OpenerMockOpenParams{url},
		expectationOrigins: OpenerMockOpenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOpen.expectations = append(mmOpen.expectations, expectation)
	return expectation
}

// Then sets up opener.Open return parameters for the expectation previously defined by the When method
func (e *OpenerMockOpenExpectation) Then(err error) *OpenerMock {
	e.results = &OpenerMockOpenResults{err}
	return e.mock
}

// Times sets number of times opener.Open should be invoked
func (mmOpen *mOpenerMockOpen) Times(n uint64) *mOpenerMockOpen {
	if n == 0 {
		mmOpen.mock.t.Fatalf("Times of OpenerMock.Open mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOpen.expectedInvocations, n)
	mmOpen.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOpen
}

func (mmOpen *mOpenerMockOpen) invocationsDone() bool {
	if len(mmOpen.expectations) == 0 && mmOpen.defaultExpectation == nil && mmOpen.mock.funcOpen == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOpen.mock.afterOpenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOpen.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Open implements opener
func (mmOpen *OpenerMock) Open(url string) (err error) {
	mm_atomic.AddUint64(&mmOpen.beforeOpenCounter, 1)
	defer mm_atomic.AddUint64(&mmOpen.afterOpenCounter, 1)

	mmOpen.t.Helper()

	if mmOpen.inspectFuncOpen != nil {
		mmOpen.inspectFuncOpen(url)
	}

	mm_params := OpenerMockOpenParams{url}

	// Record call args
	mmOpen.OpenMock.mutex.Lock()
	mmOpen.OpenMock.callArgs = append(mmOpen.OpenMock.callArgs, &mm_params)
	mmOpen.OpenMock.mutex.Unlock()

	for _, e := range mmOpen.OpenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmOpen.OpenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOpen.OpenMock.defaultExpectation.Counter, 1)
		mm_want := mmOpen.OpenMock.defaultExpectation.params
		mm_want_ptrs := mmOpen.OpenMock.defaultExpectation.paramPtrs

		mm_got := OpenerMockOpenParams{url}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.url != nil && !minimock.Equal(*mm_want_ptrs.url, mm_got.url) {
				mmOpen.t.Errorf("OpenerMock.Open got unexpected parameter url, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOpen.OpenMock.defaultExpectation.expectationOrigins.originUrl, *mm_want_ptrs.url, mm_got.url, minimock.Diff(*mm_want_ptrs.url, mm_got.url))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOpen.t.Errorf("OpenerMock.Open got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOpen.OpenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOpen.OpenMock.defaultExpectation.results
		if mm_results == nil {
			mmOpen.t.Fatal("No results are set for the OpenerMock.Open")
		}
		return (*mm_results).err
	}
	if mmOpen.funcOpen != nil {
		return mmOpen.funcOpen(url)
	}
	mmOpen.t.Fatalf("Unexpected call to OpenerMock.Open. %v", url)
	return
}

// OpenAfterCounter returns a count of finished OpenerMock.Open invocations
func (mmOpen *OpenerMock) OpenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOpen.afterOpenCounter)
}

// OpenBeforeCounter returns a count of OpenerMock.Open invocations
func (mmOpen *OpenerMock) OpenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOpen.beforeOpenCounter)
}

// Calls returns a list of arguments used in each call to OpenerMock.Open.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOpen *mOpenerMockOpen) Calls() []*OpenerMockOpenParams {
	mmOpen.mutex.RLock()

	argCopy := make([]*OpenerMockOpenParams, len(mmOpen.callArgs))
	copy(argCopy, mmOpen.callArgs)

	mmOpen.mutex.RUnlock()

	return argCopy
}

// MinimockOpenDone returns true if the count of the Open invocations corresponds
// the number of defined expectations
func (m *OpenerMock) MinimockOpenDone() bool {
	if m.OpenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OpenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OpenMock.invocationsDone()
}

// MinimockOpenInspect logs each unmet expectation
func (m *OpenerMock) MinimockOpenInspect() {
	for _, e := range m.OpenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OpenerMock.Open at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOpenCounter := mm_atomic.LoadUint64(&m.afterOpenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OpenMock.defaultExpectation != nil && afterOpenCounter < 1 {
		if m.OpenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OpenerMock.Open at\n%s", m.OpenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OpenerMock.Open at\n%s with params: %#v", m.OpenMock.defaultExpectation.expectationOrigins.origin, *m.OpenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOpen != nil && afterOpenCounter < 1 {
		m.t.Errorf("Expected call to OpenerMock.Open at\n%s", m.funcOpenOrigin)
	}

	if !m.OpenMock.invocationsDone() && afterOpenCounter > 0 {
		m.t.Errorf("Expected %d calls to OpenerMock.Open at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OpenMock.expectedInvocations), m.OpenMock.expectedInvocationsOrigin, afterOpenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OpenerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockOpenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OpenerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OpenerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockOpenDone()
}
