// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package bot

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/IlyasYOY/telethings/internal/thingsreader"
	"github.com/gojuno/minimock/v3"
)

// TaskStoreMock implements taskStore
type TaskStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSaveTaskList          func(chatID int64, scope string, startNumber int, tasks []thingsreader.Task) (err error)
	funcSaveTaskListOrigin    string
	inspectFuncSaveTaskList   func(chatID int64, scope string, startNumber int, tasks []thingsreader.Task)
	afterSaveTaskListCounter  uint64
	beforeSaveTaskListCounter uint64
	SaveTaskListMock          mTaskStoreMockSaveTaskList

	funcTaskByNumber          func(chatID int64, number int) (t1 thingsreader.Task, err error)
	funcTaskByNumberOrigin    string
	inspectFuncTaskByNumber   func(chatID int64, number int)
	afterTaskByNumberCounter  uint64
	beforeTaskByNumberCounter uint64
	TaskByNumberMock          mTaskStoreMockTaskByNumber
}

// NewTaskStoreMock returns a mock for taskStore
func NewTaskStoreMock(t minimock.Tester) *TaskStoreMock {
	m := &TaskStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveTaskListMock = mTaskStoreMockSaveTaskList{mock: m}
	m.SaveTaskListMock.callArgs = []*TaskStoreMockSaveTaskListParams{}

	m.TaskByNumberMock = mTaskStoreMockTaskByNumber{mock: m}
	m.TaskByNumberMock.callArgs = []*TaskStoreMockTaskByNumberParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTaskStoreMockSaveTaskList struct {
	optional           bool
	mock               *TaskStoreMock
	defaultExpectation *TaskStoreMockSaveTaskListExpectation
	expectations       []*TaskStoreMockSaveTaskListExpectation

	callArgs []*TaskStoreMockSaveTaskListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TaskStoreMockSaveTaskListExpectation specifies expectation struct of the taskStore.SaveTaskList
type TaskStoreMockSaveTaskListExpectation struct {
	mock               *TaskStoreMock
	params             *TaskStoreMockSaveTaskListParams
	paramPtrs          *TaskStoreMockSaveTaskListParamPtrs
	expectationOrigins TaskStoreMockSaveTaskListExpectationOrigins
	results            *TaskStoreMockSaveTaskListResults
	returnOrigin       string
	Counter            uint64
}

// TaskStoreMockSaveTaskListParams contains parameters of the taskStore.SaveTaskList
type TaskStoreMockSaveTaskListParams struct {
	chatID      int64
	scope       string
	startNumber int
	tasks       []thingsreader.Task
}

// TaskStoreMockSaveTaskListParamPtrs contains pointers to parameters of the taskStore.SaveTaskList
type TaskStoreMockSaveTaskListParamPtrs struct {
	chatID      *int64
	scope       *string
	startNumber *int
	tasks       *[]thingsreader.Task
}

// TaskStoreMockSaveTaskListResults contains results of the taskStore.SaveTaskList
type TaskStoreMockSaveTaskListResults struct {
	err error
}

// TaskStoreMockSaveTaskListOrigins contains origins of expectations of the taskStore.SaveTaskList
type TaskStoreMockSaveTaskListExpectationOrigins struct {
	origin            string
	originChatID      string
	originScope       string
	originStartNumber string
	originTasks       string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Optional() *mTaskStoreMockSaveTaskList {
	mmSaveTaskList.optional = true
	return mmSaveTaskList
}

// Expect sets up expected params for taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Expect(chatID int64, scope string, startNumber int, tasks []thingsreader.Task) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{}
	}

	if mmSaveTaskList.defaultExpectation.paramPtrs != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by ExpectParams functions")
	}

	mmSaveTaskList.defaultExpectation.params = &TaskStoreMockSaveTaskListParams{chatID, scope, startNumber, tasks}
	mmSaveTaskList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveTaskList.expectations {
		if minimock.Equal(e.params, mmSaveTaskList.defaultExpectation.params) {
			mmSaveTaskList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveTaskList.defaultExpectation.params)
		}
	}

	return mmSaveTaskList
}

// ExpectChatIDParam1 sets up expected param chatID for taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) ExpectChatIDParam1(chatID int64) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{}
	}

	if mmSaveTaskList.defaultExpectation.params != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Expect")
	}

	if mmSaveTaskList.defaultExpectation.paramPtrs == nil {
		mmSaveTaskList.defaultExpectation.paramPtrs = &TaskStoreMockSaveTaskListParamPtrs{}
	}
	mmSaveTaskList.defaultExpectation.paramPtrs.chatID = &chatID
	mmSaveTaskList.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmSaveTaskList
}

// ExpectScopeParam2 sets up expected param scope for taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) ExpectScopeParam2(scope string) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{}
	}

	if mmSaveTaskList.defaultExpectation.params != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Expect")
	}

	if mmSaveTaskList.defaultExpectation.paramPtrs == nil {
		mmSaveTaskList.defaultExpectation.paramPtrs = &TaskStoreMockSaveTaskListParamPtrs{}
	}
	mmSaveTaskList.defaultExpectation.paramPtrs.scope = &scope
	mmSaveTaskList.defaultExpectation.expectationOrigins.originScope = minimock.CallerInfo(1)

	return mmSaveTaskList
}

// ExpectStartNumberParam3 sets up expected param startNumber for taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) ExpectStartNumberParam3(startNumber int) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{}
	}

	if mmSaveTaskList.defaultExpectation.params != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Expect")
	}

	if mmSaveTaskList.defaultExpectation.paramPtrs == nil {
		mmSaveTaskList.defaultExpectation.paramPtrs = &TaskStoreMockSaveTaskListParamPtrs{}
	}
	mmSaveTaskList.defaultExpectation.paramPtrs.startNumber = &startNumber
	mmSaveTaskList.defaultExpectation.expectationOrigins.originStartNumber = minimock.CallerInfo(1)

	return mmSaveTaskList
}

// ExpectTasksParam4 sets up expected param tasks for taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) ExpectTasksParam4(tasks []thingsreader.Task) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{}
	}

	if mmSaveTaskList.defaultExpectation.params != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Expect")
	}

	if mmSaveTaskList.defaultExpectation.paramPtrs == nil {
		mmSaveTaskList.defaultExpectation.paramPtrs = &TaskStoreMockSaveTaskListParamPtrs{}
	}
	mmSaveTaskList.defaultExpectation.paramPtrs.tasks = &tasks
	mmSaveTaskList.defaultExpectation.expectationOrigins.originTasks = minimock.CallerInfo(1)

	return mmSaveTaskList
}

// Inspect accepts an inspector function that has same arguments as the taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Inspect(f func(chatID int64, scope string, startNumber int, tasks []thingsreader.Task)) *mTaskStoreMockSaveTaskList {
	if mmSaveTaskList.mock.inspectFuncSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("Inspect function is already set for TaskStoreMock.SaveTaskList")
	}

	mmSaveTaskList.mock.inspectFuncSaveTaskList = f

	return mmSaveTaskList
}

// Return sets up results that will be returned by taskStore.SaveTaskList
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Return(err error) *TaskStoreMock {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	if mmSaveTaskList.defaultExpectation == nil {
		mmSaveTaskList.defaultExpectation = &TaskStoreMockSaveTaskListExpectation{mock: mmSaveTaskList.mock}
	}
	mmSaveTaskList.defaultExpectation.results = &TaskStoreMockSaveTaskListResults{err}
	mmSaveTaskList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveTaskList.mock
}

// Set uses given function f to mock the taskStore.SaveTaskList method
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Set(f func(chatID int64, scope string, startNumber int, tasks []thingsreader.Task) (err error)) *TaskStoreMock {
	if mmSaveTaskList.defaultExpectation != nil {
		mmSaveTaskList.mock.t.Fatalf("Default expectation is already set for the taskStore.SaveTaskList method")
	}

	if len(mmSaveTaskList.expectations) > 0 {
		mmSaveTaskList.mock.t.Fatalf("Some expectations are already set for the taskStore.SaveTaskList method")
	}

	mmSaveTaskList.mock.funcSaveTaskList = f
	mmSaveTaskList.mock.funcSaveTaskListOrigin = minimock.CallerInfo(1)
	return mmSaveTaskList.mock
}

// When sets expectation for the taskStore.SaveTaskList which will trigger the result defined by the following
// Then helper
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) When(chatID int64, scope string, startNumber int, tasks []thingsreader.Task) *TaskStoreMockSaveTaskListExpectation {
	if mmSaveTaskList.mock.funcSaveTaskList != nil {
		mmSaveTaskList.mock.t.Fatalf("TaskStoreMock.SaveTaskList mock is already set by Set")
	}

	expectation := &TaskStoreMockSaveTaskListExpectation{
		mock:               mmSaveTaskList.mock,
		params:             &TaskStoreMockSaveTaskListParams{chatID, scope, startNumber, tasks},
		expectationOrigins: TaskStoreMockSaveTaskListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveTaskList.expectations = append(mmSaveTaskList.expectations, expectation)
	return expectation
}

// Then sets up taskStore.SaveTaskList return parameters for the expectation previously defined by the When method
func (e *TaskStoreMockSaveTaskListExpectation) Then(err error) *TaskStoreMock {
	e.results = &TaskStoreMockSaveTaskListResults{err}
	return e.mock
}

// Times sets number of times taskStore.SaveTaskList should be invoked
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Times(n uint64) *mTaskStoreMockSaveTaskList {
	if n == 0 {
		mmSaveTaskList.mock.t.Fatalf("Times of TaskStoreMock.SaveTaskList mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveTaskList.expectedInvocations, n)
	mmSaveTaskList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveTaskList
}

func (mmSaveTaskList *mTaskStoreMockSaveTaskList) invocationsDone() bool {
	if len(mmSaveTaskList.expectations) == 0 && mmSaveTaskList.defaultExpectation == nil && mmSaveTaskList.mock.funcSaveTaskList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveTaskList.mock.afterSaveTaskListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveTaskList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveTaskList implements taskStore
func (mmSaveTaskList *TaskStoreMock) SaveTaskList(chatID int64, scope string, startNumber int, tasks []thingsreader.Task) (err error) {
	mm_atomic.AddUint64(&mmSaveTaskList.beforeSaveTaskListCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveTaskList.afterSaveTaskListCounter, 1)

	mmSaveTaskList.t.Helper()

	if mmSaveTaskList.inspectFuncSaveTaskList != nil {
		mmSaveTaskList.inspectFuncSaveTaskList(chatID, scope, startNumber, tasks)
	}

	mm_params := TaskStoreMockSaveTaskListParams{chatID, scope, startNumber, tasks}

	// Record call args
	mmSaveTaskList.SaveTaskListMock.mutex.Lock()
	mmSaveTaskList.SaveTaskListMock.callArgs = append(mmSaveTaskList.SaveTaskListMock.callArgs, &mm_params)
	mmSaveTaskList.SaveTaskListMock.mutex.Unlock()

	for _, e := range mmSaveTaskList.SaveTaskListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveTaskList.SaveTaskListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveTaskList.SaveTaskListMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveTaskList.SaveTaskListMock.defaultExpectation.params
		mm_want_ptrs := mmSaveTaskList.SaveTaskListMock.defaultExpectation.paramPtrs

		mm_got := TaskStoreMockSaveTaskListParams{chatID, scope, startNumber, tasks}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmSaveTaskList.t.Errorf("TaskStoreMock.SaveTaskList got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveTaskList.SaveTaskListMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.scope != nil && !minimock.Equal(*mm_want_ptrs.scope, mm_got.scope) {
				mmSaveTaskList.t.Errorf("TaskStoreMock.SaveTaskList got unexpected parameter scope, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveTaskList.SaveTaskListMock.defaultExpectation.expectationOrigins.originScope, *mm_want_ptrs.scope, mm_got.scope, minimock.Diff(*mm_want_ptrs.scope, mm_got.scope))
			}

			if mm_want_ptrs.startNumber != nil && !minimock.Equal(*mm_want_ptrs.startNumber, mm_got.startNumber) {
				mmSaveTaskList.t.Errorf("TaskStoreMock.SaveTaskList got unexpected parameter startNumber, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveTaskList.SaveTaskListMock.defaultExpectation.expectationOrigins.originStartNumber, *mm_want_ptrs.startNumber, mm_got.startNumber, minimock.Diff(*mm_want_ptrs.startNumber, mm_got.startNumber))
			}

			if mm_want_ptrs.tasks != nil && !minimock.Equal(*mm_want_ptrs.tasks, mm_got.tasks) {
				mmSaveTaskList.t.Errorf("TaskStoreMock.SaveTaskList got unexpected parameter tasks, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveTaskList.SaveTaskListMock.defaultExpectation.expectationOrigins.originTasks, *mm_want_ptrs.tasks, mm_got.tasks, minimock.Diff(*mm_want_ptrs.tasks, mm_got.tasks))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveTaskList.t.Errorf("TaskStoreMock.SaveTaskList got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveTaskList.SaveTaskListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveTaskList.SaveTaskListMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveTaskList.t.Fatal("No results are set for the TaskStoreMock.SaveTaskList")
		}
		return (*mm_results).err
	}
	if mmSaveTaskList.funcSaveTaskList != nil {
		return mmSaveTaskList.funcSaveTaskList(chatID, scope, startNumber, tasks)
	}
	mmSaveTaskList.t.Fatalf("Unexpected call to TaskStoreMock.SaveTaskList. %v %v %v %v", chatID, scope, startNumber, tasks)
	return
}

// SaveTaskListAfterCounter returns a count of finished TaskStoreMock.SaveTaskList invocations
func (mmSaveTaskList *TaskStoreMock) SaveTaskListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveTaskList.afterSaveTaskListCounter)
}

// SaveTaskListBeforeCounter returns a count of TaskStoreMock.SaveTaskList invocations
func (mmSaveTaskList *TaskStoreMock) SaveTaskListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveTaskList.beforeSaveTaskListCounter)
}

// Calls returns a list of arguments used in each call to TaskStoreMock.SaveTaskList.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveTaskList *mTaskStoreMockSaveTaskList) Calls() []*TaskStoreMockSaveTaskListParams {
	mmSaveTaskList.mutex.RLock()

	argCopy := make([]*TaskStoreMockSaveTaskListParams, len(mmSaveTaskList.callArgs))
	copy(argCopy, mmSaveTaskList.callArgs)

	mmSaveTaskList.mutex.RUnlock()

	return argCopy
}

// MinimockSaveTaskListDone returns true if the count of the SaveTaskList invocations corresponds
// the number of defined expectations
func (m *TaskStoreMock) MinimockSaveTaskListDone() bool {
	if m.SaveTaskListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveTaskListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveTaskListMock.invocationsDone()
}

// MinimockSaveTaskListInspect logs each unmet expectation
func (m *TaskStoreMock) MinimockSaveTaskListInspect() {
	for _, e := range m.SaveTaskListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TaskStoreMock.SaveTaskList at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveTaskListCounter := mm_atomic.LoadUint64(&m.afterSaveTaskListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveTaskListMock.defaultExpectation != nil && afterSaveTaskListCounter < 1 {
		if m.SaveTaskListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TaskStoreMock.SaveTaskList at\n%s", m.SaveTaskListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TaskStoreMock.SaveTaskList at\n%s with params: %#v", m.SaveTaskListMock.defaultExpectation.expectationOrigins.origin, *m.SaveTaskListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveTaskList != nil && afterSaveTaskListCounter < 1 {
		m.t.Errorf("Expected call to TaskStoreMock.SaveTaskList at\n%s", m.funcSaveTaskListOrigin)
	}

	if !m.SaveTaskListMock.invocationsDone() && afterSaveTaskListCounter > 0 {
		m.t.Errorf("Expected %d calls to TaskStoreMock.SaveTaskList at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveTaskListMock.expectedInvocations), m.SaveTaskListMock.expectedInvocationsOrigin, afterSaveTaskListCounter)
	}
}

type mTaskStoreMockTaskByNumber struct {
	optional           bool
	mock               *TaskStoreMock
	defaultExpectation *TaskStoreMockTaskByNumberExpectation
	expectations       []*TaskStoreMockTaskByNumberExpectation

	callArgs []*TaskStoreMockTaskByNumberParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TaskStoreMockTaskByNumberExpectation specifies expectation struct of the taskStore.TaskByNumber
type TaskStoreMockTaskByNumberExpectation struct {
	mock               *TaskStoreMock
	params             *TaskStoreMockTaskByNumberParams
	paramPtrs          *TaskStoreMockTaskByNumberParamPtrs
	expectationOrigins TaskStoreMockTaskByNumberExpectationOrigins
	results            *TaskStoreMockTaskByNumberResults
	returnOrigin       string
	Counter            uint64
}

// TaskStoreMockTaskByNumberParams contains parameters of the taskStore.TaskByNumber
type TaskStoreMockTaskByNumberParams struct {
	chatID int64
	number int
}

// TaskStoreMockTaskByNumberParamPtrs contains pointers to parameters of the taskStore.TaskByNumber
type TaskStoreMockTaskByNumberParamPtrs struct {
	chatID *int64
	number *int
}

// TaskStoreMockTaskByNumberResults contains results of the taskStore.TaskByNumber
type TaskStoreMockTaskByNumberResults struct {
	t1  thingsreader.Task
	err error
}

// TaskStoreMockTaskByNumberOrigins contains origins of expectations of the taskStore.TaskByNumber
type TaskStoreMockTaskByNumberExpectationOrigins struct {
	origin       string
	originChatID string
	originNumber string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Optional() *mTaskStoreMockTaskByNumber {
	mmTaskByNumber.optional = true
	return mmTaskByNumber
}

// Expect sets up expected params for taskStore.TaskByNumber
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Expect(chatID int64, number int) *mTaskStoreMockTaskByNumber {
	if mmTaskByNumber.mock.funcTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Set")
	}

	if mmTaskByNumber.defaultExpectation == nil {
		mmTaskByNumber.defaultExpectation = &TaskStoreMockTaskByNumberExpectation{}
	}

	if mmTaskByNumber.defaultExpectation.paramPtrs != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by ExpectParams functions")
	}

	mmTaskByNumber.defaultExpectation.params = &TaskStoreMockTaskByNumberParams{chatID, number}
	mmTaskByNumber.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTaskByNumber.expectations {
		if minimock.Equal(e.params, mmTaskByNumber.defaultExpectation.params) {
			mmTaskByNumber.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTaskByNumber.defaultExpectation.params)
		}
	}

	return mmTaskByNumber
}

// ExpectChatIDParam1 sets up expected param chatID for taskStore.TaskByNumber
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) ExpectChatIDParam1(chatID int64) *mTaskStoreMockTaskByNumber {
	if mmTaskByNumber.mock.funcTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Set")
	}

	if mmTaskByNumber.defaultExpectation == nil {
		mmTaskByNumber.defaultExpectation = &TaskStoreMockTaskByNumberExpectation{}
	}

	if mmTaskByNumber.defaultExpectation.params != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Expect")
	}

	if mmTaskByNumber.defaultExpectation.paramPtrs == nil {
		mmTaskByNumber.defaultExpectation.paramPtrs = &TaskStoreMockTaskByNumberParamPtrs{}
	}
	mmTaskByNumber.defaultExpectation.paramPtrs.chatID = &chatID
	mmTaskByNumber.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmTaskByNumber
}

// ExpectNumberParam2 sets up expected param number for taskStore.TaskByNumber
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) ExpectNumberParam2(number int) *mTaskStoreMockTaskByNumber {
	if mmTaskByNumber.mock.funcTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Set")
	}

	if mmTaskByNumber.defaultExpectation == nil {
		mmTaskByNumber.defaultExpectation = &TaskStoreMockTaskByNumberExpectation{}
	}

	if mmTaskByNumber.defaultExpectation.params != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Expect")
	}

	if mmTaskByNumber.defaultExpectation.paramPtrs == nil {
		mmTaskByNumber.defaultExpectation.paramPtrs = &TaskStoreMockTaskByNumberParamPtrs{}
	}
	mmTaskByNumber.defaultExpectation.paramPtrs.number = &number
	mmTaskByNumber.defaultExpectation.expectationOrigins.originNumber = minimock.CallerInfo(1)

	return mmTaskByNumber
}

// Inspect accepts an inspector function that has same arguments as the taskStore.TaskByNumber
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Inspect(f func(chatID int64, number int)) *mTaskStoreMockTaskByNumber {
	if mmTaskByNumber.mock.inspectFuncTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("Inspect function is already set for TaskStoreMock.TaskByNumber")
	}

	mmTaskByNumber.mock.inspectFuncTaskByNumber = f

	return mmTaskByNumber
}

// Return sets up results that will be returned by taskStore.TaskByNumber
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Return(t1 thingsreader.Task, err error) *TaskStoreMock {
	if mmTaskByNumber.mock.funcTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Set")
	}

	if mmTaskByNumber.defaultExpectation == nil {
		mmTaskByNumber.defaultExpectation = &TaskStoreMockTaskByNumberExpectation{mock: mmTaskByNumber.mock}
	}
	mmTaskByNumber.defaultExpectation.results = &TaskStoreMockTaskByNumberResults{t1, err}
	mmTaskByNumber.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTaskByNumber.mock
}

// Set uses given function f to mock the taskStore.TaskByNumber method
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Set(f func(chatID int64, number int) (t1 thingsreader.Task, err error)) *TaskStoreMock {
	if mmTaskByNumber.defaultExpectation != nil {
		mmTaskByNumber.mock.t.Fatalf("Default expectation is already set for the taskStore.TaskByNumber method")
	}

	if len(mmTaskByNumber.expectations) > 0 {
		mmTaskByNumber.mock.t.Fatalf("Some expectations are already set for the taskStore.TaskByNumber method")
	}

	mmTaskByNumber.mock.funcTaskByNumber = f
	mmTaskByNumber.mock.funcTaskByNumberOrigin = minimock.CallerInfo(1)
	return mmTaskByNumber.mock
}

// When sets expectation for the taskStore.TaskByNumber which will trigger the result defined by the following
// Then helper
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) When(chatID int64, number int) *TaskStoreMockTaskByNumberExpectation {
	if mmTaskByNumber.mock.funcTaskByNumber != nil {
		mmTaskByNumber.mock.t.Fatalf("TaskStoreMock.TaskByNumber mock is already set by Set")
	}

	expectation := &TaskStoreMockTaskByNumberExpectation{
		mock:               mmTaskByNumber.mock,
		params:             &TaskStoreMockTaskByNumberParams{chatID, number},
		expectationOrigins: TaskStoreMockTaskByNumberExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTaskByNumber.expectations = append(mmTaskByNumber.expectations, expectation)
	return expectation
}

// Then sets up taskStore.TaskByNumber return parameters for the expectation previously defined by the When method
func (e *TaskStoreMockTaskByNumberExpectation) Then(t1 thingsreader.Task, err error) *TaskStoreMock {
	e.results = &TaskStoreMockTaskByNumberResults{t1, err}
	return e.mock
}

// Times sets number of times taskStore.TaskByNumber should be invoked
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Times(n uint64) *mTaskStoreMockTaskByNumber {
	if n == 0 {
		mmTaskByNumber.mock.t.Fatalf("Times of TaskStoreMock.TaskByNumber mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTaskByNumber.expectedInvocations, n)
	mmTaskByNumber.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTaskByNumber
}

func (mmTaskByNumber *mTaskStoreMockTaskByNumber) invocationsDone() bool {
	if len(mmTaskByNumber.expectations) == 0 && mmTaskByNumber.defaultExpectation == nil && mmTaskByNumber.mock.funcTaskByNumber == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTaskByNumber.mock.afterTaskByNumberCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTaskByNumber.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// TaskByNumber implements taskStore
func (mmTaskByNumber *TaskStoreMock) TaskByNumber(chatID int64, number int) (t1 thingsreader.Task, err error) {
	mm_atomic.AddUint64(&mmTaskByNumber.beforeTaskByNumberCounter, 1)
	defer mm_atomic.AddUint64(&mmTaskByNumber.afterTaskByNumberCounter, 1)

	mmTaskByNumber.t.Helper()

	if mmTaskByNumber.inspectFuncTaskByNumber != nil {
		mmTaskByNumber.inspectFuncTaskByNumber(chatID, number)
	}

	mm_params := TaskStoreMockTaskByNumberParams{chatID, number}

	// Record call args
	mmTaskByNumber.TaskByNumberMock.mutex.Lock()
	mmTaskByNumber.TaskByNumberMock.callArgs = append(mmTaskByNumber.TaskByNumberMock.callArgs, &mm_params)
	mmTaskByNumber.TaskByNumberMock.mutex.Unlock()

	for _, e := range mmTaskByNumber.TaskByNumberMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.t1, e.results.err
		}
	}

	if mmTaskByNumber.TaskByNumberMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTaskByNumber.TaskByNumberMock.defaultExpectation.Counter, 1)
		mm_want := mmTaskByNumber.TaskByNumberMock.defaultExpectation.params
		mm_want_ptrs := mmTaskByNumber.TaskByNumberMock.defaultExpectation.paramPtrs

		mm_got := TaskStoreMockTaskByNumberParams{chatID, number}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmTaskByNumber.t.Errorf("TaskStoreMock.TaskByNumber got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTaskByNumber.TaskByNumberMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.number != nil && !minimock.Equal(*mm_want_ptrs.number, mm_got.number) {
				mmTaskByNumber.t.Errorf("TaskStoreMock.TaskByNumber got unexpected parameter number, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTaskByNumber.TaskByNumberMock.defaultExpectation.expectationOrigins.originNumber, *mm_want_ptrs.number, mm_got.number, minimock.Diff(*mm_want_ptrs.number, mm_got.number))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTaskByNumber.t.Errorf("TaskStoreMock.TaskByNumber got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTaskByNumber.TaskByNumberMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTaskByNumber.TaskByNumberMock.defaultExpectation.results
		if mm_results == nil {
			mmTaskByNumber.t.Fatal("No results are set for the TaskStoreMock.TaskByNumber")
		}
		return (*mm_results).t1, (*mm_results).err
	}
	if mmTaskByNumber.funcTaskByNumber != nil {
		return mmTaskByNumber.funcTaskByNumber(chatID, number)
	}
	mmTaskByNumber.t.Fatalf("Unexpected call to TaskStoreMock.TaskByNumber. %v %v", chatID, number)
	return
}

// TaskByNumberAfterCounter returns a count of finished TaskStoreMock.TaskByNumber invocations
func (mmTaskByNumber *TaskStoreMock) TaskByNumberAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTaskByNumber.afterTaskByNumberCounter)
}

// TaskByNumberBeforeCounter returns a count of TaskStoreMock.TaskByNumber invocations
func (mmTaskByNumber *TaskStoreMock) TaskByNumberBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTaskByNumber.beforeTaskByNumberCounter)
}

// Calls returns a list of arguments used in each call to TaskStoreMock.TaskByNumber.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTaskByNumber *mTaskStoreMockTaskByNumber) Calls() []*TaskStoreMockTaskByNumberParams {
	mmTaskByNumber.mutex.RLock()

	argCopy := make([]*TaskStoreMockTaskByNumberParams, len(mmTaskByNumber.callArgs))
	copy(argCopy, mmTaskByNumber.callArgs)

	mmTaskByNumber.mutex.RUnlock()

	return argCopy
}

// MinimockTaskByNumberDone returns true if the count of the TaskByNumber invocations corresponds
// the number of defined expectations
func (m *TaskStoreMock) MinimockTaskByNumberDone() bool {
	if m.TaskByNumberMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TaskByNumberMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TaskByNumberMock.invocationsDone()
}

// MinimockTaskByNumberInspect logs each unmet expectation
func (m *TaskStoreMock) MinimockTaskByNumberInspect() {
	for _, e := range m.TaskByNumberMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TaskStoreMock.TaskByNumber at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTaskByNumberCounter := mm_atomic.LoadUint64(&m.afterTaskByNumberCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TaskByNumberMock.defaultExpectation != nil && afterTaskByNumberCounter < 1 {
		if m.TaskByNumberMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TaskStoreMock.TaskByNumber at\n%s", m.TaskByNumberMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TaskStoreMock.TaskByNumber at\n%s with params: %#v", m.TaskByNumberMock.defaultExpectation.expectationOrigins.origin, *m.TaskByNumberMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTaskByNumber != nil && afterTaskByNumberCounter < 1 {
		m.t.Errorf("Expected call to TaskStoreMock.TaskByNumber at\n%s", m.funcTaskByNumberOrigin)
	}

	if !m.TaskByNumberMock.invocationsDone() && afterTaskByNumberCounter > 0 {
		m.t.Errorf("Expected %d calls to TaskStoreMock.TaskByNumber at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TaskByNumberMock.expectedInvocations), m.TaskByNumberMock.expectedInvocationsOrigin, afterTaskByNumberCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TaskStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveTaskListInspect()

			m.MinimockTaskByNumberInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TaskStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TaskStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveTaskListDone() &&
		m.MinimockTaskByNumberDone()
}
